language: ruby
rvm:
- 2.6.1
gemfile:
- Gemfile
cache:
- bundler
script: bin/test
before_install:
- gem update --system
- gem install bundler -v '2.0.1'
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
- psql -c 'create database db_test;' -U postgres

addons:
  postgresql: "9.6"

deploy:
  provider: heroku
  api_key:
    secure: 5d4cd4ee-ab00-4782-ba94-61e53e4a6e8e
    app: chat-room-056
    on:
      repo: saikat-org/chat_room
env:
  global:
    secure: F6RMRp3EqJegV6We8AoOCPXIAsqklI+3+yFW4xB7PTwNMeqTSN5ebQrzLgIKxS2wEkTeOQkPBTk6R68culelKqvAA2cbco0RqK+4KlFabGsU1phxO0WrM4QAMqQ3Kd1qbl8lkPovJOwunnQJn9NsYLrCeoWlH6ymSjJdkGffp0Nd1uuMFWL1a/JXhbmAjfTtxdD2BPVY0YfKhjr8BrhrLAsEhcYmxh7Aig1G0JCT1Kbv2ZdxwE6fqH46cskxk1IhjFSd/HW5WRzwavsHcc9T8tS7Xbfu/3ClKKUCvECxhau8yecR7x+vCFmodjpZ6aSZhrSZX++wiFuGw+vXZopfWMicUiHeFmMFuTT0dHjkmkDxSfABSaAbHbTGrgsskpEmZWXGj09B/TR4Vvhq2UUzrQ4IzlGcMP0v4b+snkPBb1qDM1gsfnORCT6l5+/kkGAWR3nnjZlubVrfvuLQX4HM7OCXEeGDlOuunL9+J6Gwn8PtnWF+AQioi/w3JQR/9waRLvVKem9FbVTWMaoHFH3py7aI85JdtjMokbCtTaWSnfKSkUW91nxNgSU7/3ZY9np8FazrtyzL6+jN0PjnMA0L6Nbl02elzCQYANnLV6xoYa1IGrbJuTv2YaJTWH5F6LbptmNQHHY/RBbwI47GJkmC21X2aD26Fv6+AMEGV3vHn1s=
